name: Newline Check
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  newline-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check newline at end of files
        run: ./.github/scripts/newline-check.sh
