name: Rime
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        path: 
          - cyan-or-less
          - straight-conditions
          - fffffx
          - unions
          - x-word-database
          - lcm-and-gcd
          - range-rotate-query
          - long-chess-board
          - counting-zig-zag-sequence
          - subset-mex
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rime
        run: pip install rime

      - name: Install pypy
        run: sudo apt-get install pypy3

      - name: Rime test
        run: rime test ${{ matrix.path }} -k
