name: Rime
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt install build-essential
          pip install rime

      - name: Rime test
        run: rime test x-word-database
