name: Rime
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rime
        run: pip install rime

      - name: Install pypy
        run: sudo apt-get install pypy3

      - uses: ./.github/actions/rime-test
        with:
          problem: cyan-or-less

      - uses: ./.github/actions/rime-test
        with:
          problem: fffffx

      - uses: ./.github/actions/rime-test
        with:
          problem: unions

      - uses: ./.github/actions/rime-test
        with:
          problem: x-word-database

      - uses: ./.github/actions/rime-test
        with:
          problem: lcm-and-gcd

      - uses: ./.github/actions/rime-test
        with:
          problem: range-rotate-query

      - uses: ./.github/actions/rime-test
        with:
          problem: long-chess-board

      - uses: ./.github/actions/rime-test
        with:
          problem: counting-zig-zag-sequence

      - uses: ./.github/actions/rime-test
        with:
          problem: deque-inversion

      - uses: ./.github/actions/rime-test
        with:
          problem: subset-mex

