name: Rime
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rime and pypy
        run: |
          pip install rime
          sudo apt-get install pypy3


      - name: Run Rime tests
        run: |
          problems=(
            "cyan-or-less"
            "fffffx"
            "unions"
            "x-word-database"
            "lcm-and-gcd"
            "range-rotate-query"
            "long-chess-board"
            "counting-zig-zag-sequence"
            "deque-inversion"
            "subset-mex"
          )
          for problem in "${problems[@]}"; do
            echo "Testing $problem"
            ./.github/actions/rime-test "${problem}"
          done
